# Generated by Django 5.2.7 on 2026-03-26 00:08

import django.db.models.deletion
import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('confirmation_number', models.CharField(default=reservations.models.generate_confirmation_number, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('hotel_name', models.CharField(max_length=255)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_list', to='reservations.reservation')),
            ],
        ),
    ]
